server:
  servlet:
    context-path: /
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  main:
    banner-mode: off
  aop:
    proxy-target-class: true
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 10s

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Actuator endpoints
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always